import { addMissingColumns } from './helpers';
import type { Migration } from './types';

/** The columns of the Impulse personnel form (Додаток 1), one text column each. */
const CARD_COLUMNS = [
    'passportType',
    'passportSeries',
    'passportNumber',
    'passportIssuer',
    'passportIssueDate',
    'foreignPassportNumber',
    'foreignPassportIssuer',
    'foreignPassportIssueDate',
    'militaryTicketSeries',
    'militaryTicketNumber',
    'militaryTicketIssuer',
    'militaryTicketIssueDate',
    'ubdSeries',
    'ubdNumber',
    'ubdIssuer',
    'ubdIssueDate',
    'driverLicenseCategories',
    'driverLicenseSeries',
    'driverLicenseNumber',
    'driverLicenseIssuer',
    'driverLicenseIssueDate',
    'driverLicenseValidUntil',
    'drivingExperience',
    'tractorLicenseCategories',
    'tractorLicenseSeries',
    'tractorLicenseNumber',
    'tractorLicenseIssuer',
    'tractorLicenseIssueDate',
    'tractorLicenseValidUntil',
    'tractorExperience',
    'iban',
    'bankCard',
    'bankName',
    'regRegion',
    'regDistrict',
    'regSettlement',
    'regCityDistrict',
    'regStreetType',
    'regStreet',
    'regHouse',
    'regFlat',
    'liveRegion',
    'liveDistrict',
    'liveSettlement',
    'liveCityDistrict',
    'liveStreetType',
    'liveStreet',
    'liveHouse',
    'liveFlat',
    'extraPhone',
    'citizenship',
    'birthCountry',
    'nationality',
    'tags',
    'rankOrderNumber',
    'rankOrderIssuer',
    'appointmentOrderDate',
    'appointmentOrderNumber',
    'appointmentOrderIssuer',
    'drillOrderDate',
    'drillOrderNumber',
    'drillOrderIssuer',
    'bzvpFrom',
    'bzvpTo',
    'bzvpPlace',
    'bzvpCommander',
    'bzvpComment',
    'academicTitle',
    'academicTitleAssignedBy',
    'academicTitleDate',
    'scientificWorks',
    'electedBody',
    'electedDate',
    'electedUntil',
    'electedPosition',
    'oathDate',
    'conscriptionDate',
    'enlistmentOrderDate',
    'enlistmentOrderNumber',
    'serviceLengthDate',
    'serviceLength',
    'preferentialServiceLengthDate',
    'preferentialServiceLength',
];

/**
 * Особова картка as in Impulse: documents, addresses, service, bank details… in the columns of
 * the Impulse import form instead of one free-text field per document. The old free-text
 * fields stay untouched (they keep what was imported from Excel). `educationList` and
 * `awardRecords` are JSON arrays: the lines of Impulse «Освіта і курси» and the awards.
 */
export const personalCard: Migration = {
    version: 10,
    name: 'personal-card',
    async up(db) {
        await addMissingColumns(db, 'users', {
            ...Object.fromEntries(CARD_COLUMNS.map((column) => [column, 'TEXT'])),
            educationList: "TEXT NOT NULL DEFAULT '[]'",
            awardRecords: "TEXT NOT NULL DEFAULT '[]'",
        });
    },
};
